---

- name: install ELK stack
  hosts: all
  become: True
  vars_files:
      - docker_vars.yml
  tasks:
    - name: install ubuntu packages
      apt:
        name: "{{ ubuntu_packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: install redhat packages
      yum:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: add Ubuntu GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: add docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker
      when: ansible_os_family == "Debian"

    - name: add docker repo for RedHat
      yum_repository:
        name: docker
        description: docker repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        state: present
        file: docker
      when: ansible_os_family == "RedHat"

    - name: update caches for ubuntu
      apt:
         update_cache: yes
      when: ansible_os_family == "Debian"

    - name: update caches for redhat
      yum:
        name: "*"
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: install docker on ubuntu
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    - name: install docker on radhat
      yum:
        name: docker-ce
        state: present
      when: ansible_os_family == "RedHat"
