---

- name: install ELK stack
  hosts: all
  become: True
  vars_files:
      - vars.yml
  tasks:
    - name: install ubuntu packages
      apt:
        name: {{ ubuntu_packages }}
        state: present
      when: ansible_os_family == "Debian"

    - name: install redhat packages
      yum:
        name: {{ redhat_packages }}
        state: present
      when: ansible_os_family == "RedHat"

   - name: add Ubuntu GPG key
     apt-key:
       url: "https://download.docker.com/linux/ubuntu/gpg"
       state: present
     when: ansible_os_family == "Debian"
